language: node_js

node_js:
- node

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- npm test

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: npm
  email: cestaro.lorenzo@gmail.com
  api_key:
    secure: ilCA+QCiq2dnqHo60Tum1FT8FbJoneCfofDZcIn4ZWtcaQbH+hdP/kcNQ6IuHZKfaVKbnTEoPvXhevJ5TxflH41Am1LBSouKl8Nx2q+dg1wdc/oir9qMD3WoExD41wMv5TiqgECeWmOx4iZK7iieRwmgUNF8GJmuM08ZTdYJKRtdDKuCInkOw00UNFwSZvr+Lny4TqczPsO1c3NCjNddSwPJ4LinyBVq60wEhn49XSOnn80JHhvACx1W+MO/QvI6IquBIN+pr21yFTzW8Aeye33GvvBmp2VQNBA3hXsQ4gi0k4N/X94xkBTpfrAmQEcW1bs/VQfg5uNoLW/MkSf+LDzV0xDZVvC8n5yrm0UY4VLDLsgEV5LctcxQCRniiqkiuA++NgIf1II+3NtJKnTOUV60yrGBDRm8gSds2u8+T5ILmjEgvBwzgSsKmaP722/rzDOkX2+gDgb5S7ZpUKWi+4vkxvth1GuO3m1I85marcCG60TCWDA4aqVqGkPbEsj5fDsBCzLYulStvae+B5ze8rFxhyypoOs8RrVqHQ+CKLShrOWIEeoPNvWfBl+Hb5NZ7IOuvR/RiNZPtJVLXSiaI7W0GqPqrJQuh+ViduDQDiV2d154HNaB2zgnlBQv1xL8h6gHviZsNCuWslyrJaZgO5u4jxGFQlu2VBI7MkmrmHM=
  on:
    tags: true
    repo: lorenzocestaro/seqalign
    branch: master
